# Generated by Django 3.2.5 on 2022-08-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='summary',
            new_name='sumary',
        ),
    ]
